--- 
name: slack_webhook_basic
on: 
  push:
    branches:
      - main
permissions:
  contents : read
  
jobs:
  build:  
    name: Build and Test 
    runs-on: ubuntu-latest 
    permissions: 
      contents: read 
      actions: read 
    steps: 
    - name: Checkout 
      uses: actions/checkout@v4
    - name: Build project 
      run: |
        echo "Build Project" 
    - name: Run tests
      run: |
        echo "Run Test" 
    - name: action-slack
      if: always()
      uses: 8398a7/action-slack@v3.2.0
      env: 
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        status: ${{job.status}} 
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        author_name: Github Action Slack 
        message: ${{ github.event.head_commit.message }}

