--- 
name: slack_webhook_basic
on: workflow_dispatch 
jobs:
  build:  
    name: Build and Test 
    runs-on: ubuntu-latest 
    permissions: 
      contents: read 
      actions: read 
    steps: 
    - name: Checkout 
      uses: actions/checkout@v2 
    - name: Build project 
      run: |
        echo "Build Project" 
    - name: Run tests
      run: |
        echo "Run Test" 
    - name: Notice when a build finishes 
      if: always()
      uses: 8398a7/action-slack@v3.2.0
      env: 
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        status: ${{job.status}} 
        fields: repo,message,workflow,job,ref
        author_name: Github Action Slack 

